/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PersonWrapper */

#ifndef _Included_PersonWrapper
#define _Included_PersonWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PersonWrapper
 * Method:    createPerson
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_PersonWrapper_createPerson
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     PersonWrapper
 * Method:    setName
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_PersonWrapper_setName
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     PersonWrapper
 * Method:    getName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_PersonWrapper_getName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     PersonWrapper
 * Method:    setAge
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_PersonWrapper_setAge
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     PersonWrapper
 * Method:    getAge
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_PersonWrapper_getAge
  (JNIEnv *, jobject, jlong);

/*
 * Class:     PersonWrapper
 * Method:    freePerson
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_PersonWrapper_freePerson
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
